service:
  name: ${file(./modules/sanitizeStackName.js):sanitize}

plugins:
  - serverless-s3-sync
  - serverless-pseudo-parameters
  - serverless-stack-output
  - serverless-cloudfront-invalidate

custom:

  # The domain name to be used
  domainName: ${opt:domain}

  # API base path
  basePath: 'v1'

  # API endpoint type
  endpointType: 'EDGE'

  # API Gateway settings
  apiGateway:
    # See https://docs.aws.amazon.com/general/latest/gr/rande.html#apigateway_region
    hostedZone: 'Z2FDTNDATAQYW2'

  # Output plugin configuration
  output:
    handler: modules/output.handler

  # CloudFront invalidation plugin configuration
  cloudfrontInvalidate:
    distributionIdKey: 'CloudFrontDistributionId'
    items: # Add your files to invalidate here:
      - '/index.html'

  # S3 sync plugin configuration
  s3Sync:
    - bucketName: ${opt:domain}
      localDir: website

provider:
  name: aws
  runtime: nodejs10.x
  region: ${opt:region, 'us-east-1'}
  # Deployment bucket settings
  deploymentBucket:
    name: 'serverless-deployment-bucket-562552715877'
    serverSideEncryption: AES256
  # API Gateway settings
  apiGateway:
    restApiId: '#{ApiGatewayRestApi}'
    restApiRootResourceId: '#{ApiGatewayRestApi.RootResourceId}'

functions:
  api:
    handler: api/baseApi.router
    memorySize: 256
    timeout: 5
    environment:
      AWS_NODEJS_CONNECTION_REUSE_ENABLED: '1' # Enable HTTP keep-alive connections for the AWS SDK
      DOMAIN_NAME: '${self:custom.domainName}'
      BASE_PATH: '${self:custom.basePath}'
    events:
      - http:
          path: '{proxy+}'
          method: any

resources:
  - ${file(resources/api-gw.yml)}
  - ${file(resources/api-gw-basepath-mapping.yml)}
  - ${file(resources/api-gw-domain-name.yml)}
  - ${file(resources/custom-acm-certificate-lambda.yml)}
  - ${file(resources/custom-acm-certificate-lambda-role.yml)}
  - ${file(resources/cloudfront-origin-access-identity.yml)}
  - ${file(resources/s3-bucket.yml)}
  - ${file(resources/s3-policies.yml)}
  - ${file(resources/hosted-zone.yml)}
  - ${file(resources/dns-records.yml)}
  - ${file(resources/certificate.yml)}
  - ${file(resources/cf-distribution.yml)}
  - ${file(resources/outputs.yml)}

package:
  exclude:
    - docs/**
    - modules/**
    - resources/**
    - website/**
    - LICENSE
    - README.md
